CREATE ROLE user_api WITH LOGIN;
CREATE DATABASE userdb;
GRANT ALL PRIVILEGES ON DATABASE userdb TO user_api;
\c userdb;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS citext;
